-- ==============================================================================
-- Supabase PostgreSQL Schema សម្រាប់ប្រព័ន្ធគ្រប់គ្រងហិរញ្ញវត្ថុ PAC Finance App
-- បណ្ឌិត្យសភានគរបាលកម្ពុជា
-- ==============================================================================

-- ១. បង្កើត Table pac_ledger (បញ្ជីចំណូល-ចំណាយ)
CREATE TABLE IF NOT EXISTS public.pac_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    label TEXT NOT NULL DEFAULT '',
    inc_usd NUMERIC(15, 2) DEFAULT 0,
    inc_khr NUMERIC(15, 2) DEFAULT 0,
    exp_usd NUMERIC(15, 2) DEFAULT 0,
    exp_khr NUMERIC(15, 2) DEFAULT 0,
    is_opening BOOLEAN NOT NULL DEFAULT FALSE,
    receipt_url TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- បន្ថែម Column receipt_url ប្រសិនបើតារាងមានស្រាប់
ALTER TABLE public.pac_ledger ADD COLUMN IF NOT EXISTS receipt_url TEXT DEFAULT '';

-- ២. បង្កើត Table pac_invoices (របាយការណ៍វិក្កយបត្រថ្នាក់ដឹកនាំ)
CREATE TABLE IF NOT EXISTS public.pac_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    inv_no TEXT NOT NULL DEFAULT '',
    label TEXT NOT NULL DEFAULT '',
    amount_usd NUMERIC(15, 2) DEFAULT 0,
    amount_khr NUMERIC(15, 2) DEFAULT 0,
    receipt_url TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- បន្ថែម Column receipt_url ប្រសិនបើតារាងមានស្រាប់
ALTER TABLE public.pac_invoices ADD COLUMN IF NOT EXISTS receipt_url TEXT DEFAULT '';

-- ៣. បើក Row Level Security (RLS) ដើម្បីគ្រប់គ្រងសិទ្ធិ
ALTER TABLE public.pac_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pac_invoices ENABLE ROW LEVEL SECURITY;

-- ៤. បង្កើត Policy អនុញ្ញាតឱ្យអាន សរសេរ កែប្រែ និងលុប (Full Access ជាមួយ Anon Public Key)
DROP POLICY IF EXISTS "Public access for pac_ledger" ON public.pac_ledger;
CREATE POLICY "Public access for pac_ledger" ON public.pac_ledger
    FOR ALL
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public access for pac_invoices" ON public.pac_invoices;
CREATE POLICY "Public access for pac_invoices" ON public.pac_invoices
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ៥. បើក Realtime ដើម្បីឱ្យរាល់ពេលមានទិន្នន័យថ្មី វានឹង Update លើគ្រប់កុំព្យូទ័រ/ទូរស័ព្ទភ្លាមៗ
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'pac_ledger'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.pac_ledger;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'pac_invoices'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.pac_invoices;
    END IF;
END $$;

-- ៦. បង្កើត Storage Bucket សម្រាប់ផ្ទុករូបភាពវិក្កយបត្រ (pac_receipts)
INSERT INTO storage.buckets (id, name, public)
VALUES ('pac_receipts', 'pac_receipts', true)
ON CONFLICT (id) DO NOTHING;

-- ៧. បង្កើត Policy សម្រាប់ Storage Bucket pac_receipts
DROP POLICY IF EXISTS "Public view for pac_receipts" ON storage.objects;
CREATE POLICY "Public view for pac_receipts" ON storage.objects
    FOR SELECT USING (bucket_id = 'pac_receipts');

DROP POLICY IF EXISTS "Public upload for pac_receipts" ON storage.objects;
CREATE POLICY "Public upload for pac_receipts" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'pac_receipts');

DROP POLICY IF EXISTS "Public update for pac_receipts" ON storage.objects;
CREATE POLICY "Public update for pac_receipts" ON storage.objects
    FOR UPDATE USING (bucket_id = 'pac_receipts');

DROP POLICY IF EXISTS "Public delete for pac_receipts" ON storage.objects;
CREATE POLICY "Public delete for pac_receipts" ON storage.objects
    FOR DELETE USING (bucket_id = 'pac_receipts');

-- ៨. បញ្ចូលទិន្នន័យគំរូដំបូង (ប្រសិនបើតារាងនៅទំនេរ)
INSERT INTO public.pac_ledger (date, label, inc_usd, inc_khr, exp_usd, exp_khr, is_opening)
SELECT '2026-08-01', 'ថវិកានៅសល់', 0, 20000000, 0, 0, false
WHERE NOT EXISTS (SELECT 1 FROM public.pac_ledger LIMIT 1);

INSERT INTO public.pac_invoices (date, inv_no, label, amount_usd, amount_khr)
SELECT '2026-08-01', 'INV-001', 'ថ្លៃអាហារទទួលភ្ញៀវប្រតិភូ', 120, 0
WHERE NOT EXISTS (SELECT 1 FROM public.pac_invoices LIMIT 1);

-- ៩. បង្កើត Table pac_settings សម្រាប់ Sync លេខកូដ PIN និងការកំណត់ផ្សេងៗឆ្លង Device (Computer & Phone)
CREATE TABLE IF NOT EXISTS public.pac_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- បើក RLS សម្រាប់ pac_settings
ALTER TABLE public.pac_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access for pac_settings" ON public.pac_settings;
CREATE POLICY "Public access for pac_settings" ON public.pac_settings
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- បើក Realtime សម្រាប់ pac_settings
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'pac_settings'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.pac_settings;
    END IF;
END $$;

-- បញ្ចូល Default PINs ប្រសិនបើមិនទាន់មាន
INSERT INTO public.pac_settings (key, value)
VALUES 
    ('pin_viewer', '1111'),
    ('pin_editor', '123455')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

